import 'package:flutter/material.dart';
import 'package:flutterapp/kulinercirebonapp/generatedandroidsmall3widget/generated/GeneratedFrame1Widget3.dart';
import 'package:flutterapp/kulinercirebonapp/generatedandroidsmall3widget/generated/GeneratedVector1Widget3.dart';
import 'package:flutterapp/kulinercirebonapp/generatedandroidsmall3widget/generated/GeneratedLockWidget6.dart';
import 'package:flutterapp/kulinercirebonapp/generatedandroidsmall3widget/generated/GeneratedAccount_circleWidget10.dart';
import 'package:flutterapp/kulinercirebonapp/generatedandroidsmall3widget/generated/GeneratedVectorWidget10.dart';
import 'package:flutterapp/kulinercirebonapp/generatedandroidsmall3widget/generated/GeneratedVectorWidget12.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/kulinercirebonapp/generatedandroidsmall3widget/generated/GeneratedVectorWidget11.dart';
import 'package:flutterapp/kulinercirebonapp/generatedandroidsmall3widget/generated/GeneratedVector2Widget3.dart';
import 'package:flutterapp/kulinercirebonapp/generatedandroidsmall3widget/generated/GeneratedAccount_circleWidget8.dart';
import 'package:flutterapp/kulinercirebonapp/generatedandroidsmall3widget/generated/GeneratedPutrijelbungagmailcomWidget.dart';
import 'package:flutterapp/kulinercirebonapp/generatedandroidsmall3widget/generated/GeneratedPutriJelitaBungaWidget.dart';
import 'package:flutterapp/kulinercirebonapp/generatedandroidsmall3widget/generated/GeneratedDaftarAkunWidget1.dart';

/* Frame Android Small - 3
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedAndroidSmall3Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: null,
                top: null,
                right: 117.0,
                bottom: 183.0,
                width: 134.0,
                height: 40.0,
                child: GeneratedFrame1Widget3(),
              ),
              Positioned(
                left: 0.0,
                top: 289.0,
                right: 0.0,
                bottom: null,
                width: null,
                height: 0.0,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width = constraints.maxWidth - 72.0;
                  final double scaleX = width <= 0 ? 0 : (width / 303.0);

                  final Widget child = GeneratedVector1Widget3();
                  return Stack(children: [
                    Transform(
                      transform: Matrix4(scaleX, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1,
                          0, 19.0 * scaleX, 289.0, 0, 1),
                      alignment: Alignment.topLeft,
                      child: SizedBox.expand(child: child),
                    )
                  ]);
                }),
              ),
              Positioned(
                left: 17.0,
                top: 148.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedAccount_circleWidget8(),
              ),
              Positioned(
                left: 18.0,
                top: 261.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedLockWidget6(),
              ),
              Positioned(
                left: 106.0,
                top: 48.0,
                right: 119.0,
                bottom: null,
                width: null,
                height: 30.0,
                child: GeneratedDaftarAkunWidget1(),
              ),
              Positioned(
                left: 0.0,
                top: 176.0,
                right: 0.0,
                bottom: null,
                width: null,
                height: 0.0,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width = constraints.maxWidth - 72.0;
                  final double scaleX = width <= 0 ? 0 : (width / 303.0);

                  final Widget child = GeneratedVector2Widget3();
                  return Stack(children: [
                    Transform(
                      transform: Matrix4(scaleX, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1,
                          0, 18.0 * scaleX, 176.0, 0, 1),
                      alignment: Alignment.topLeft,
                      child: SizedBox.expand(child: child),
                    )
                  ]);
                }),
              ),
              Positioned(
                left: 54.0,
                top: 148.0,
                right: null,
                bottom: null,
                width: 88.0,
                height: 18.0,
                child: GeneratedPutriJelitaBungaWidget(),
              ),
              Positioned(
                left: 17.0,
                top: 204.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedAccount_circleWidget10(),
              ),
              Positioned(
                left: 54.0,
                top: 204.0,
                right: null,
                bottom: null,
                width: 134.0,
                height: 21.0,
                child: GeneratedPutrijelbungagmailcomWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.09166666666666666;
                  double scaleX =
                      (constraints.maxWidth * percentWidth) / 34.375;

                  double percentHeight = 0.010937500469790303;
                  double scaleY = (constraints.maxHeight * percentHeight) /
                      8.881250381469727;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.175,
                        translateY: constraints.maxHeight * 0.4078124849667103,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget10())
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.09166666666666666;
                  double scaleX =
                      (constraints.maxWidth * percentWidth) / 34.375;

                  double percentHeight = 0.010937500469790303;
                  double scaleY = (constraints.maxHeight * percentHeight) /
                      8.881250381469727;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.38888887532552086,
                        translateY: constraints.maxHeight * 0.4078124849667103,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget11())
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.09166666666666666;
                  double scaleX =
                      (constraints.maxWidth * percentWidth) / 34.375;

                  double percentHeight = 0.010937500469790303;
                  double scaleY = (constraints.maxHeight * percentHeight) /
                      8.881250381469727;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.2833333333333333,
                        translateY: constraints.maxHeight * 0.4078124849667103,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget12())
                  ]);
                }),
              )
            ]),
      ),
    ));
  }
}
