import 'package:flutter/material.dart';
import 'package:flutterapp/kulinercirebonapp/generatedandroidsmall5widget/generated/GeneratedLupapasswordWidget1.dart';
import 'package:flutterapp/kulinercirebonapp/generatedandroidsmall5widget/generated/GeneratedEmailWidget1.dart';
import 'package:flutterapp/kulinercirebonapp/generatedandroidsmall5widget/generated/GeneratedVector2Widget1.dart';
import 'package:flutterapp/kulinercirebonapp/generatedandroidsmall5widget/generated/GeneratedBelumPunyaAkunDaftarWidget1.dart';
import 'package:flutterapp/kulinercirebonapp/generatedandroidsmall5widget/generated/GeneratedAccount_circleWidget2.dart';
import 'package:flutterapp/kulinercirebonapp/generatedandroidsmall5widget/generated/GeneratedWidget.dart';
import 'package:flutterapp/kulinercirebonapp/generatedandroidsmall5widget/generated/GeneratedLillypongWidget.dart';
import 'package:flutterapp/kulinercirebonapp/generatedandroidsmall5widget/generated/GeneratedMasukWidget2.dart';
import 'package:flutterapp/kulinercirebonapp/generatedandroidsmall5widget/generated/GeneratedFrame1Widget1.dart';
import 'package:flutterapp/kulinercirebonapp/generatedandroidsmall5widget/generated/GeneratedPasswordWidget1.dart';
import 'package:flutterapp/kulinercirebonapp/generatedandroidsmall5widget/generated/GeneratedVector1Widget1.dart';
import 'package:flutterapp/kulinercirebonapp/generatedandroidsmall5widget/generated/GeneratedLockWidget2.dart';

/* Frame Android Small - 5
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedAndroidSmall5Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 119.0,
                top: null,
                right: 100.0,
                bottom: 44.0,
                width: null,
                height: 16.0,
                child: GeneratedBelumPunyaAkunDaftarWidget1(),
              ),
              Positioned(
                left: null,
                top: null,
                right: 107.0,
                bottom: 84.0,
                width: 137.0,
                height: 40.0,
                child: GeneratedFrame1Widget1(),
              ),
              Positioned(
                left: 0.0,
                top: 460.0,
                right: 0.0,
                bottom: null,
                width: null,
                height: 0.0,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width = constraints.maxWidth - 72.0;
                  final double scaleX = width <= 0 ? 0 : (width / 303.0);

                  final Widget child = GeneratedVector1Widget1();
                  return Stack(children: [
                    Transform(
                      transform: Matrix4(scaleX, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1,
                          0, 36.0 * scaleX, 460.0, 0, 1),
                      alignment: Alignment.topLeft,
                      child: SizedBox.expand(child: child),
                    )
                  ]);
                }),
              ),
              Positioned(
                left: 35.0,
                top: 354.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedAccount_circleWidget2(),
              ),
              Positioned(
                left: 35.0,
                top: 432.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedLockWidget2(),
              ),
              Positioned(
                left: 149.0,
                top: 56.0,
                right: 144.0,
                bottom: null,
                width: null,
                height: 31.0,
                child: GeneratedMasukWidget2(),
              ),
              Positioned(
                left: 0.0,
                top: 382.0,
                right: 0.0,
                bottom: null,
                width: null,
                height: 0.0,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width = constraints.maxWidth - 72.0;
                  final double scaleX = width <= 0 ? 0 : (width / 303.0);

                  final Widget child = GeneratedVector2Widget1();
                  return Stack(children: [
                    Transform(
                      transform: Matrix4(scaleX, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1,
                          0, 36.0 * scaleX, 382.0, 0, 1),
                      alignment: Alignment.topLeft,
                      child: SizedBox.expand(child: child),
                    )
                  ]);
                }),
              ),
              Positioned(
                left: 67.0,
                top: 334.0,
                right: null,
                bottom: null,
                width: 33.0,
                height: 21.0,
                child: GeneratedEmailWidget1(),
              ),
              Positioned(
                left: 67.0,
                top: 359.0,
                right: null,
                bottom: null,
                width: 50.0,
                height: 21.0,
                child: GeneratedLillypongWidget(),
              ),
              Positioned(
                left: 241.0,
                top: 475.0,
                right: null,
                bottom: null,
                width: 85.0,
                height: 18.0,
                child: GeneratedLupapasswordWidget1(),
              ),
              Positioned(
                left: 67.0,
                top: 409.0,
                right: null,
                bottom: null,
                width: 54.0,
                height: 21.0,
                child: GeneratedPasswordWidget1(),
              ),
              Positioned(
                left: 67.0,
                top: 438.0,
                right: null,
                bottom: null,
                width: 86.0,
                height: 21.0,
                child: GeneratedWidget(),
              )
            ]),
      ),
    ));
  }
}
